name: ci

env:
  AWS_REGION: ap-southeast-1
  ECR_REPO: 725753070509.dkr.ecr.ap-southeast-1.amazonaws.com/ecs-poc-frontend
  TASK_DEFINITION: ecs-poc-dev
  ECS_CLUSTER: ecs-poc-dev-cluster
  ECS_SERVICE: ecs-poc-dev
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      image-tag: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ap-southeast-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - name: Build Docker image
        id: build-image
        run: |
          IMAGE_TAG=$ECR_REPO:${GITHUB_SHA}
          docker build -t $IMAGE_TAG .
          echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Push to ECR
        run: |
          docker push ${{ steps.build-image.outputs.image }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ap-southeast-1

      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.TASK_DEFINITION }} \
            --query 'taskDefinition | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' \
            > task-definition.json

      - name: Render task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1.8.3
        with:
          task-definition: task-definition.json
          container-name: frontend
          image: ${{ needs.build-and-push.outputs.image-tag }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          cluster: ${{ env.ECS_CLUSTER }}
          service: ${{ env.ECS_SERVICE }}
          wait-for-service-stability: true
