name: cicd

env:
  AWS_REGION: ap-southeast-1
  ECR_REPO: 725753070509.dkr.ecr.ap-southeast-1.amazonaws.com/ecs-poc-frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ap-southeast-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - name: Build Docker image
        run: |
          docker build -t $ECR_REPO:${GITHUB_SHA} .

      - name: Push to ECR
        run: |
          docker push $ECR_REPO:${GITHUB_SHA}
